# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./blogr-nextjs-prisma

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./blogr-nextjs-prisma/package-lock.json
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Check formatting
        run: npm run prettier:check

      # - name: Build application
      #   run: npm run build --if-present

      # - name: Run unit tests
      #   run: npm run test

      # - env:
      #     POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      #     POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      #     POSTGRES_URL_NO_SSL: ${{ secrets.POSTGRES_URL_NO_SSL }}
      #     POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      #   name: Run application in background
      #   run: npm run dev &

      # - name: Run end to end tests
      #   run: npm run cypress:run

      # - name: Upload screenshots
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: blogr-nextjs-prisma/cypress/screenshots
